[2018-10-09 08:21:04,156] ERROR task_19: cannot get frame #0
Traceback (most recent call last):
  File "/home/yilinma/Documents/LabellingTool/cvat/cvat/apps/engine/views.py", line 120, in get_frame
    return sendfile(request, path)
  File "/home/yilinma/Documents/LabellingTool/cvat/cvat/venv_labelling_tool/lib/python3.6/site-packages/sendfile/__init__.py", line 59, in sendfile
    raise Http404('"%s" does not exist' % filename)
django.http.response.Http404: "/home/yilinma/Documents/LabellingTool/cvat/data/19/data/0/0/0.jpg" does not exist
